api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/yarn"
  id = "paketo-buildpacks/yarn"
  name = "Paketo Yarn Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/yarn/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default_versions]
    yarn = "1.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:yarnpkg:yarn:1.22.18:*:*:*:*:*:*:*"
    id = "yarn"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Yarn"
    purl = "pkg:generic/yarn@1.22.18?checksum=816e5c073b3d35936a398d1fe769ebbcd517298e3510b649e8fc67cd3a62e113&download_url=https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-v1.22.18.tar.gz"
    sha256 = "f1c14b6b5a18a1a6d6dbe1e113f62b3d1fe11aee2855b6c9cfe7079480a64db7"
    source = "https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-v1.22.18.tar.gz"
    source_sha256 = "816e5c073b3d35936a398d1fe769ebbcd517298e3510b649e8fc67cd3a62e113"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "<UNKNOWN>"
    version = "1.22.18"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:yarnpkg:yarn:1.22.19:*:*:*:*:*:*:*"
    id = "yarn"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Yarn"
    purl = "pkg:generic/yarn@1.22.19?checksum=732620bac8b1690d507274f025f3c6cfdc3627a84d9642e38a07452cc00e0f2e&download_url=https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-v1.22.19.tar.gz"
    sha256 = "3fff3fb2684f8f87984db0ca5b6575b9dba7ee0f09127d9ecd85c1594c3e4c2d"
    source = "https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-v1.22.19.tar.gz"
    source_sha256 = "732620bac8b1690d507274f025f3c6cfdc3627a84d9642e38a07452cc00e0f2e"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "<UNKNOWN>"
    version = "1.22.19"

  [[metadata.dependency-constraints]]
    constraint = "1.*"
    id = "yarn"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
