api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/yarn"
  id = "paketo-buildpacks/yarn"
  name = "Paketo Yarn Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/yarn/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default_versions]
    yarn = "1.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:yarn:yarn:yarn:*:*:*:*:ruby:*:*"
    id = "yarn"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Yarn"
    purl = "pkg:generic/yarn@1.22.18?checksum=fake-sha&download_url=https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-v1.22.18.tar.gz"
    sha256 = "96e9d10debb3d28dc98064c9f74b687ce4a2d90016efc244e81d86a430d57ed1"
    source = "https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-v1.22.18.tar.gz"
    source_sha256 = "fake-sha"
    stacks = ["io.paketo.stacks.bionic"]
    uri = "<UNKNOWN>"
    version = "1.22.18"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:yarn:yarn:yarn:*:*:*:*:ruby:*:*"
    id = "yarn"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Yarn"
    purl = "pkg:generic/yarn@1.22.19?checksum=fake-sha&download_url=https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-v1.22.19.tar.gz"
    sha256 = "6692cb835ff57095c2117df482d6b07075c5a10d8293ae68e7a884ddbdc2364a"
    source = "https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-v1.22.19.tar.gz"
    source_sha256 = "fake-sha"
    stacks = ["io.paketo.stacks.bionic"]
    uri = "<UNKNOWN>"
    version = "1.22.19"

  [[metadata.dependency-constraints]]
    constraint = "1.*"
    id = "yarn"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
